"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";

const stages = [["01", "PROBLEM", "Real problems exist everywhere.", "⌕"], ["02", "UNDERSTANDING", "We dig deep to see what's true.", "♧"], ["03", "STRATEGY", "We reframe and find the right way.", "↗"], ["04", "CREATION", "We build systems, products and experiences.", "◇"], ["05", "IMPACT", "We create value that moves people forward.", "◎"]];
const directions = [["01", "INDUSTRY SOLUTIONS", "We find problems worth solving across industries and build solutions that create real impact.", "industry"], ["02", "BUSINESS & PRODUCT STRATEGY", "We help businesses and products reach their true potential with the right strategy, systems and execution.", "strategy"], ["03", "INNOVATION & COMMUNITY", "We create platforms for ideas, run hackathons, empower students and inspire the next generation of builders.", "community"]];
const thinking = [["01", "CURIOUS", "We ask questions before making assumptions.", "⌕"], ["02", "RESTLESS", "We don't accept that 'that's how it's always been done.'", "ϟ"], ["03", "PRACTICAL", "A beautiful idea means little if it cannot work.", "⚒"], ["04", "EXPERIMENTAL", "We prototype, test and learn continuously.", "⚗"], ["05", "LONG-TERM", "We care about what happens after launch.", "↗"]];
const people = [["MUKESHKUMAR", "Founder & Product Strategist", "Problem finder, product thinker. Builder at heart.", "MK", "/assets/people/mukeshkumar-profile.png"], ["ROWFIN", "Co-founder & Growth", "Turns ideas into momentum and connects the dots.", "R", "/assets/people/rowfin-profile.png"], ["DESIGN PARTNER", "Experience & Interface", "Designs clarity into every interaction.", "DP", "/assets/people/design-partner-profile.png"], ["TECH PARTNER", "Engineering & Systems", "Builds robust systems that scale.", "TP", "/assets/people/tech-partner-profile.png"]];
const pillars = [["⌁", "FOUNDERS", "Vision & leadership to spark what's next."], ["◇", "STUDENTS", "Ideas & energy to challenge the status quo."], ["□", "BUILDERS", "Code & craft to turn ideas into reality."], ["✦", "DESIGNERS", "Experience & aesthetics to make it human."], ["♧", "MENTORS", "Guidance & wisdom to shape the right path."], ["↗", "PARTNERS", "Scale & reach to expand the impact."]];
const milestones = [["2024", "Builstry begins.", "⌁"], ["2024", "First problems we chose to solve.", "◇"], ["2025", "First solutions built and launched.", "□"], ["2025", "First businesses we partnered with.", "✦"], ["2026", "First hackathons and community.", "♧"], ["2026+", "Many more problems to solve. Many more to build.", "◎"]];
const standards = [["CLARITY", "OVER COMPLEXITY", "We choose simple, clear thinking over unnecessary complexity."], ["EVIDENCE", "OVER ASSUMPTIONS", "We rely on what's real, not what's assumed."], ["USEFUL", "OVER IMPRESSIVE", "We build what creates real value, not what just looks good."], ["LONG-TERM", "OVER SHORT-TERM", "We care about lasting impact, not quick wins."], ["BUILDING", "OVER TALKING", "We turn ideas into real solutions."]];

function HeroVisual() { return <div className="about-ref-hero-visual" aria-hidden="true"><div className="about-ref-hero-glow" /><div className="about-ref-hero-grid" /><div className="about-ref-hero-beam about-ref-hero-beam-one" /><div className="about-ref-hero-beam about-ref-hero-beam-two" /><div className="about-ref-hero-signal about-ref-hero-signal-one" /><div className="about-ref-hero-signal about-ref-hero-signal-two" /><div className="about-ref-hero-figure" /><div className="about-ref-cube"><i /><i /><i /></div></div>; }

export default function AboutReferencePage() {
  const [activeStage, setActiveStage] = useState(0), [activeDirection, setActiveDirection] = useState(null), [activeThinking, setActiveThinking] = useState(null), [hoveredThinking, setHoveredThinking] = useState(null), [activePerson, setActivePerson] = useState(null), [hoveredPerson, setHoveredPerson] = useState(null), [dragStart, setDragStart] = useState(null);
  const whyRef = useRef(null);
  useEffect(() => { const section = whyRef.current; if (!section) return; const timer = window.setInterval(() => { if (document.visibilityState === "visible") setActiveStage((current) => (current + 1) % stages.length); }, 3200); return () => window.clearInterval(timer); }, []);
  useEffect(() => { const journey = document.querySelector(".about-ref-journey"); if (!journey) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { journey.classList.add("is-visible"); observer.disconnect(); } }, { threshold: 0.18 }); observer.observe(journey); return () => observer.disconnect(); }, []);
  const moveStage = (index) => setActiveStage(Math.max(0, Math.min(stages.length - 1, index)));
  const keyStage = (event) => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) event.preventDefault(); if (event.key === "ArrowLeft") moveStage(activeStage - 1); if (event.key === "ArrowRight") moveStage(activeStage + 1); if (event.key === "Home") moveStage(0); if (event.key === "End") moveStage(stages.length - 1); };
  const selectDirection = (index) => setActiveDirection((current) => current === index ? null : index);
  const activePersonIndex = hoveredPerson ?? activePerson;
  return <main className="about-reference-page about-website-reference">
    <div className="about-ref-progress" aria-hidden="true"><span /></div>
    <section className="about-ref-hero"><div className="about-ref-hero-copy"><h1><span>WE DIDN&apos;T START WITH A COMPANY.</span><span className="accent">WE STARTED WITH A WAY OF LOOKING AT PROBLEMS.</span></h1><p>We believe meaningful things are built when people question what already exists, understand what isn&apos;t working, and create what should come next.</p></div><div className="about-ref-hero-art"><HeroVisual /><div className="about-ref-hero-label">THINK → BUILD → IMPACT</div></div></section>
    <section ref={whyRef} className="about-ref-why"><div className="about-ref-why-copy"><h2>WHY <em>BUILSTRY</em> EXISTS</h2><p>Technology is advancing faster than ever. But technology alone doesn&apos;t make something valuable.</p><p>The valuable part is knowing what deserves to be built, why it matters, and how to make it work.</p><p>Builstry brings those stages together.</p><div className="about-ref-status"><b>{String(activeStage + 1).padStart(2, "0")}</b><span>/ 05</span></div></div><div className="about-ref-fan"><div className="about-ref-fan-stage" tabIndex="0" role="region" aria-label="Why Builstry stages" onKeyDown={keyStage} onPointerDown={(event) => { setDragStart(event.clientX); event.currentTarget.setPointerCapture?.(event.pointerId); }} onPointerUp={(event) => { if (dragStart === null) return; const distance = event.clientX - dragStart; if (Math.abs(distance) > 42) moveStage(activeStage + (distance < 0 ? 1 : -1)); setDragStart(null); }} onPointerCancel={() => setDragStart(null)}>{stages.map(([number, title, text, icon], index) => { const offset = index - activeStage; const position = offset < -1 ? "far-left" : offset > 1 ? "far-right" : offset === -1 ? "left-1" : offset === 0 ? "active" : "right-1"; return <button type="button" className={`about-ref-fan-card ${position}`} key={title} onClick={() => moveStage(index)} aria-label={`Show ${title}`} aria-current={index === activeStage ? "true" : undefined}><span className="about-ref-stage-index">{number}</span><span className="about-ref-stage-icon">{icon}</span><span className="about-ref-fan-copy"><b>{title}</b><small>{text}</small></span><span className="about-ref-stage-footer">BUILSTRY / {number}</span></button>; })}</div><div className="about-ref-fan-controls"><button type="button" onClick={() => moveStage(activeStage - 1)} disabled={activeStage === 0}>←</button><div>{stages.map(([number], index) => <i className={index === activeStage ? "is-active" : ""} key={number} />)}</div><button type="button" onClick={() => moveStage(activeStage + 1)} disabled={activeStage === stages.length - 1}>→</button></div></div></section>
    <section className="about-ref-directions"><div className="about-ref-section-title"><span className="about-ref-kicker">HOW WE TURN BELIEF INTO MOTION</span><h2>THREE DIRECTIONS. <em>ONE BELIEF.</em></h2></div><div className="about-ref-directions-grid has-selection" data-selected={activeDirection === null ? 0 : activeDirection + 1}>{directions.map(([number, title, text, visual], index) => <article className={`about-ref-direction-card ${visual} ${activeDirection === index ? "is-selected" : activeDirection !== null ? "is-dimmed" : ""}`} key={number} role="button" tabIndex="0" onClick={() => selectDirection(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); selectDirection(index); } }}><div className="about-ref-direction-visual"><span /><span /><span /></div><div className="about-ref-direction-content"><span>{number}</span><h3>{title}</h3><p>{text}</p><span className="about-ref-circle-link">→</span></div></article>)}</div><Link href="/capabilities" className="about-ref-link">Explore what we do →</Link></section>
    <section className="about-ref-thinking"><div className="about-ref-thinking-intro"><span className="about-ref-kicker">THE MINDSET</span><h2>HOW <em>WE</em> THINK</h2><p>Our mindset shapes everything we build — from the questions we ask to the solutions we create.</p></div><div className="about-ref-thinking-grid">{thinking.map(([number, title, text, icon], index) => <article className={(hoveredThinking ?? activeThinking) === index ? "is-active" : ""} key={number} tabIndex="0" onMouseEnter={() => setHoveredThinking(index)} onMouseLeave={() => setHoveredThinking(null)} onFocus={() => setHoveredThinking(index)} onBlur={() => setHoveredThinking(null)} onClick={() => setActiveThinking(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setActiveThinking(index); }}><div><span>{icon}</span><small>{number}</small></div><h3>{title}</h3><p>{text}</p><footer><i />→</footer></article>)}</div></section>
    <section className="about-ref-people"><div className="about-ref-people-intro"><span className="about-ref-kicker">WHO BUILDS IT</span><h2>THE PEOPLE<br />BEHIND <em>BUILSTRY</em></h2><p>A small team with a big mission. Driven by curiosity, craft and conviction, we turn ideas into meaningful products.</p><Link href="/careers" className="about-ref-link">Join our journey →</Link><div className="about-ref-people-stats"><span><b>4</b><small>CORE<br />MEMBERS</small></span><span><b>∞</b><small>BIG<br />IDEAS</small></span><span><b>1</b><small>SHARED<br />MISSION</small></span></div></div><div className="about-ref-people-showcase"><div className="about-ref-people-grid">{people.map(([name, role, bio, initials, image], index) => <article className={activePersonIndex === index ? "is-active" : ""} key={name} tabIndex="0" onMouseEnter={() => setHoveredPerson(index)} onMouseLeave={() => setHoveredPerson(null)} onFocus={() => setHoveredPerson(index)} onBlur={() => setHoveredPerson(null)} onClick={() => setActivePerson(index)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setActivePerson(index); }}><div className="about-ref-person-photo"><img src={image} alt={`${name} profile portrait`} loading="lazy" /><small>{String(index + 1).padStart(2, "0")}</small><span>{initials}</span></div><div className="about-ref-person-info"><h3>{name}</h3><b>{role}</b><i /><p>{bio}</p><div className="about-ref-person-footer"><span>in</span><span>View Profile →</span></div></div></article>)}</div><div className="about-ref-people-controls"><button type="button" onClick={() => setActivePerson((current) => ((current ?? 0) + people.length - 1) % people.length)}>←</button><div>{people.map(([name], index) => <i className={activePersonIndex === index ? "is-active" : ""} key={name} />)}</div><button type="button" onClick={() => setActivePerson((current) => ((current ?? -1) + 1) % people.length)}>→</button></div></div></section>
    <section className="about-ref-team"><div className="about-ref-team-intro"><span className="about-ref-kicker">THE NETWORK</span><h2>BUILSTRY<br /><em>IS BIGGER</em><br /><em>THAN</em><br />ITS TEAM</h2><p>We work with founders, mentors, researchers, students and partners to turn bold ideas into real impact.</p><Link href="/careers" className="about-ref-link">Join our journey →</Link><div className="about-ref-team-rule" /><span className="about-ref-team-note">MORE PERSPECTIVES.<br />BETTER POSSIBILITIES.</span></div><div className="about-ref-team-network"><div className="about-ref-team-grid">{pillars.map(([icon, title, text], index) => <article key={title}><div><small>{String(index + 1).padStart(2, "0")}</small><span>{icon}</span><i /></div><b>{title}</b><em>{text}</em></article>)}</div><div className="about-ref-team-stats"><span><b>5+</b><small>COMMUNITIES<br />CONNECTED</small></span><span><b>1000+</b><small>IDEAS<br />IN MOTION</small></span><span><b>∞</b><small>BIGGER<br />POSSIBILITIES</small></span><em>TOGETHER WE BUILD WHAT SHOULD EXIST.</em></div><div className="about-ref-team-footer"><span>BUILSTRY</span><i /><span>THINK</span><i /><span>BUILD</span><i /><span>IMPACT</span></div></div></section>
    <section className="about-ref-standards"><div className="about-ref-standards-copy"><span className="about-ref-kicker">OUR STANDARD</span><h2>WHAT WE<br /><em>REFUSE</em><br />TO COMPROMISE ON.</h2><p>These principles guide every idea, product and partnership we build — now and always.</p><div className="about-ref-standards-note"><i />HIGHER STANDARDS.<br />BRIGHTER OUTCOMES.</div></div><div className="about-ref-standards-list">{standards.map(([title, subtitle, text], index) => <article key={title}><div><small>{String(index + 1).padStart(2, "0")}</small><i /></div><b>{title}</b><small>{subtitle}</small><p>{text}</p></article>)}</div><div className="about-ref-standards-footer"><span>BUILSTRY</span><i /><span>THINK</span><i /><span>BUILD</span><i /><span>IMPACT</span></div></section>
    <section className="about-ref-journey"><div className="about-ref-journey-panel"><span className="about-ref-kicker">THE MILESTONES</span><h2>OUR <em>JOURNEY</em> SO FAR</h2><p>From a simple idea to real solutions — here&apos;s how we&apos;ve grown, step by step, with people who believe in what we build.</p><svg className="about-ref-journey-path" viewBox="0 0 100 520" preserveAspectRatio="none" aria-hidden="true"><path d="M50 0 C18 72 82 132 50 210 S82 348 50 520" /></svg><div className="about-ref-timeline">{milestones.map(([year, text, icon], index) => <article key={`${year}-${text}`} style={{ "--delay": `${index * 90}ms` }}><span>{icon}</span><b>{year}</b><p>{text}</p></article>)}</div></div></section>
  </main>;
}
