export const milestones = [
  {
    id: "2018",
    year: "2018",
    title: "The curiosity begins",
    description: "It began with a simple question: what if meaningful change started with asking better questions?",
    phase: "CURIOSITY",
    anchor: "Journey_2018",
    prop: "orb",
    wide: [-8.15, -2.88, 0],
    desktop: [-5.15, -2.88, 0],
    mobile: [-1.05, -3.62, 0],
  },
  {
    id: "2019",
    year: "2019",
    title: "First problems we chose to solve",
    description: "We chose real problems—not convenient ones—and learned alongside the people closest to them.",
    phase: "FIRST QUESTIONS",
    anchor: "Journey_2019",
    prop: "mountain",
    wide: [-5.56, -2.02, 0],
    desktop: [-3.43, -2.03, 0],
    mobile: [1.05, -2.41, 0],
  },
  {
    id: "2020",
    year: "2020",
    title: "A way of working takes shape",
    description: "A clearer rhythm emerged: understand the problem, find a direction, then build with care.",
    phase: "A WAY OF WORKING",
    anchor: "Journey_2020",
    prop: "layers",
    wide: [-2.95, -1.20, 0],
    desktop: [-1.72, -1.18, 0],
    mobile: [-1.05, -1.20, 0],
  },
  {
    id: "2021",
    year: "2021",
    title: "Solutions start making an impact",
    description: "Early solutions began creating practical value for teams and the people they serve.",
    phase: "EARLY IMPACT",
    anchor: "Journey_2021",
    prop: "bubbles",
    wide: [-0.35, -0.39, 0],
    desktop: [0, -0.33, 0],
    mobile: [1.05, 0.01, 0],
  },
  {
    id: "2022",
    year: "2022",
    title: "Builstry comes to life",
    description: "Builstry took shape as a home for curious people who find, think and build.",
    phase: "BUILSTRY BEGINS",
    anchor: "Journey_2022",
    prop: "cubes",
    wide: [2.26, 0.43, 0],
    desktop: [1.72, 0.52, 0],
    mobile: [-1.05, 1.22, 0],
  },
  {
    id: "2023",
    year: "2023",
    title: "Platforms, communities and growth",
    description: "Platforms and communities brought students, founders and builders together to learn and grow.",
    phase: "ECOSYSTEM GROWS",
    anchor: "Journey_2023",
    prop: "network",
    wide: [4.88, 1.24, 0],
    desktop: [3.43, 1.37, 0],
    mobile: [1.05, 2.43, 0],
  },
  {
    id: "2024+",
    year: "2024+",
    title: "Many more problems to solve. Many more to build.",
    description: "The next chapter is still being built—with more useful work, more people and more possibility.",
    phase: "THE NEXT CHAPTER",
    anchor: "Journey_2024",
    prop: "summit",
    wide: [7.50, 2.05, 0],
    desktop: [5.14, 2.22, 0],
    mobile: [0.12, 3.62, 0],
  },
];

export const getJourneyLayout = (aspect) => {
  if (aspect < 0.92) return "mobile";
  if (aspect > 1.88) return "wide";
  return "desktop";
};
